version: "3.7"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=felixyy.lee@mail.utoronto.ca
      - NGINX_PROXY_CONTAINER=nginx-proxy
  postgresdb:
    image: 'postgres:12-alpine'
    container_name: postgresdb
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
  frontend:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/vertohealthjuniors-frontend:${VERSION}
    container_name: frontend
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=felixlyy.me,www.felixlyy.me,www.mindmappers.felixlyy.me
      - LETSENCRYPT_HOST=felixlyy.me,www.felixlyy.me,www.mindmappers.felixlyy.me
  backend:
    image: ghcr.io/utsc-cscc09-programming-on-the-web/vertohealthjuniors-backend:${VERSION}
    container_name: backend
    restart: always
    depends_on:
      - postgresdb
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_HOST=api.felixlyy.me,api.mindmappers.felixlyy.me
      - LETSENCRYPT_HOST=api.felixlyy.me,api.mindmappers.felixlyy.me

volumes:
  db: