name: Backend Image Microservice CI/CD

on:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - backend/image-microservice/**
      - .github/workflows/build-backend-image.yml
env:
  IMAGE_NAME: mindmappers-backend-image-microservice

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    defaults:
      run:
        working-directory: backend/image-microservice

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build . --file Dockerfile \
          --tag $(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]') \

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
